import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import Image from "next/image";

function ShoppingCart() {
    return (
        <div>
            <Image alt="cart" src="/person-shopping.svg" width={30} height={30} />
            <div id="amt">0</div>
        </div>
    )
}

// ... rest of the code
function Navbar() {
    return (
        <nav className="outer">
            {/* image will likely go here prolly. */}
            <div className="name">yetnt</div>
            <nav className="inner">
                <div>Tracks</div>
                <div>Videos</div>
                <div>Contact</div>
                <Image alt="f" src="/search/icons8-search-150.svg" width={25} height={25} />
                <ShoppingCart />
            </nav>
        </nav>
    )
}

// ... rest of the code

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
    <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <Navbar />
            <main>
            {children}</main>
        </body>
    </html>
    );
}
